package com.github.eclipsethemes.eclipse.preferences;

public interface PreferenceKeys {
	String ACTIVE_THEME_ID = "ACTIVE_THEME_ID";
	String APPLY_WORKBENCH_THEME = "APPLY_WORKBENCH_THEME";
	String COLOR_CUSTOMIZATIONS_PREFIX = "COLOR_CUSTOMIZATIONS.";

	// Appearance options. See AppearanceSettings for the defaults.
	String FLAT_TOOLBAR_BUTTONS = "APPEARANCE.FLAT_TOOLBAR_BUTTONS";
	String MODERN_SCROLLBARS = "APPEARANCE.MODERN_SCROLLBARS";
	String SOLID_FOCUS_RINGS = "APPEARANCE.SOLID_FOCUS_RINGS";
	String ROUNDED_CONTROLS = "APPEARANCE.ROUNDED_CONTROLS";
	String DIM_SEPARATORS = "APPEARANCE.DIM_SEPARATORS";
	String ACCENT_LIST_SELECTION = "APPEARANCE.ACCENT_LIST_SELECTION";
	String SQUARE_TABS = "APPEARANCE.SQUARE_TABS";
	String CLOSE_BUTTON_ON_ACTIVE_TAB_ONLY = "APPEARANCE.CLOSE_BUTTON_ON_ACTIVE_TAB_ONLY";
	String HIDE_TAB_MINIMIZE_MAXIMIZE = "APPEARANCE.HIDE_TAB_MINIMIZE_MAXIMIZE";
}
