package com.github.eclipsethemes.eclipse.adapters.ui;

import com.github.eclipsethemes.core.models.Theme;
import com.github.eclipsethemes.core.models.TokenKey;

public final class GtkCssGenerator {

	private GtkCssGenerator() {
	}

	public static String generate(Theme theme) {
		String background = theme.get(TokenKey.BACKGROUND).getColor().toString();
		String foreground = theme.get(TokenKey.FOREGROUND).getColor().toString();
		String selectionBackground = theme.get(TokenKey.SELECTION_BACKGROUND).getColor().toString();
		String selectionForeground = theme.get(TokenKey.SELECTION_FOREGROUND).getColor().toString();

		return """
				/* Generated by Eclipse Themes. Changes are overwritten. */
				@define-color theme_bg_color %s;
				@define-color theme_fg_color %s;
				@define-color theme_base_color %s;
				@define-color theme_text_color %s;
				@define-color theme_selected_bg_color %s;
				@define-color theme_selected_fg_color %s;

				window, box, paned, notebook, toolbar {
				    background-color: @theme_bg_color;
				    color: @theme_fg_color;
				}
				*:selected, *:selected:focus, treeview.view:selected,
				treeview.view:selected:focus, list:selected, entry:selected {
				    background-color: @theme_selected_bg_color;
				    color: @theme_selected_fg_color;
				}
				"""
				.formatted(background, foreground, background, foreground, selectionBackground, selectionForeground);
	}
}
