package com.github.eclipsethemes.eclipse.adapters.ui;

import java.util.LinkedHashMap;
import java.util.Map;

import com.github.eclipsethemes.core.models.Theme;

/**
 * Generates the overlay applied after Eclipse's platform-specific base theme.
 * Keeping this separate from the base theme lets Eclipse retain its GTK, Cocoa
 * and Win32 renderer rules, its tab renderer and its layout metrics.
 *
 * <p>
 * The e4 CSS engine resolves conflicts by selector specificity first and by
 * stylesheet order second (see {@code ViewCSSImpl} and {@code StyleWrapper}).
 * Because Eclipse parses stylesheets registered through
 * {@code IThemeEngine#registerStylesheet} after the ones belonging to the
 * active theme, an overlay rule only wins when its selector is at least as
 * specific as the platform rule it replaces. A bare {@code Composite} selector
 * therefore cannot override {@code .MPart Composite} or {@code Shell Tree},
 * which is why the selectors below mirror the ones used by
 * {@code org.eclipse.ui.themes}.
 * </p>
 */
public final class WorkbenchCssGenerator {

	private WorkbenchCssGenerator() {
	}

	public static String generate(Theme theme) {
		WorkbenchPalette palette = WorkbenchPalette.of(theme);

		Map<String, String> colors = new LinkedHashMap<>();
		colors.put("background", palette.background());
		colors.put("foreground", palette.foreground());
		colors.put("chrome", palette.chrome());
		colors.put("elevated", palette.elevated());
		colors.put("hover", palette.hover());
		colors.put("input", palette.input());
		colors.put("border", palette.border());
		colors.put("muted", palette.muted());
		colors.put("disabled", palette.disabled());
		colors.put("link", palette.link());
		colors.put("selectionBackground", palette.selectionBackground());

		String css = TEMPLATE;
		for (Map.Entry<String, String> color : colors.entrySet()) {
			css = css.replace("${" + color.getKey() + "}", color.getValue());
		}
		return css;
	}

	// @formatter:off
	private static final String TEMPLATE = """
			/* Generated by Eclipse Themes. Changes are overwritten. */

			/* ===== Workbench color registry =====
			 * Eclipse's own stylesheets reference these definitions instead of literal
			 * colors, so overriding them re-themes every rule that uses them.
			 */
			ColorDefinition#org-eclipse-ui-workbench-DARK_BACKGROUND { color: ${background}; }
			ColorDefinition#org-eclipse-ui-workbench-DARK_FOREGROUND { color: ${foreground}; }
			ColorDefinition#org-eclipse-ui-workbench-LINK_COLOR { color: ${link}; }

			ColorDefinition#org-eclipse-ui-workbench-ACTIVE_TAB_BG_START { color: ${background}; }
			ColorDefinition#org-eclipse-ui-workbench-ACTIVE_TAB_BG_END { color: ${background}; }
			ColorDefinition#org-eclipse-ui-workbench-ACTIVE_TAB_TEXT_COLOR { color: ${foreground}; }
			ColorDefinition#org-eclipse-ui-workbench-ACTIVE_TAB_UNSELECTED_TEXT_COLOR { color: ${muted}; }
			ColorDefinition#org-eclipse-ui-workbench-ACTIVE_TAB_SELECTED_TEXT_COLOR { color: ${foreground}; }
			ColorDefinition#org-eclipse-ui-workbench-ACTIVE_TAB_OUTER_KEYLINE_COLOR { color: ${border}; }
			ColorDefinition#org-eclipse-ui-workbench-ACTIVE_TAB_INNER_KEYLINE_COLOR { color: ${border}; }
			ColorDefinition#org-eclipse-ui-workbench-ACTIVE_TAB_OUTLINE_COLOR { color: ${border}; }
			ColorDefinition#org-eclipse-ui-workbench-ACTIVE_UNSELECTED_TABS_COLOR_START { color: ${chrome}; }
			ColorDefinition#org-eclipse-ui-workbench-ACTIVE_UNSELECTED_TABS_COLOR_END { color: ${chrome}; }
			ColorDefinition#org-eclipse-ui-workbench-ACTIVE_NOFOCUS_TAB_BG_START { color: ${background}; }
			ColorDefinition#org-eclipse-ui-workbench-ACTIVE_NOFOCUS_TAB_BG_END { color: ${background}; }
			ColorDefinition#org-eclipse-ui-workbench-ACTIVE_NOFOCUS_TAB_TEXT_COLOR { color: ${muted}; }
			ColorDefinition#org-eclipse-ui-workbench-ACTIVE_NOFOCUS_TAB_SELECTED_TEXT_COLOR { color: ${foreground}; }

			ColorDefinition#org-eclipse-ui-workbench-INACTIVE_TAB_BG_START { color: ${chrome}; }
			ColorDefinition#org-eclipse-ui-workbench-INACTIVE_TAB_BG_END { color: ${chrome}; }
			ColorDefinition#org-eclipse-ui-workbench-INACTIVE_TAB_TEXT_COLOR { color: ${muted}; }
			ColorDefinition#org-eclipse-ui-workbench-INACTIVE_TAB_UNSELECTED_TEXT_COLOR { color: ${muted}; }
			ColorDefinition#org-eclipse-ui-workbench-INACTIVE_TAB_SELECTED_TEXT_COLOR { color: ${foreground}; }
			ColorDefinition#org-eclipse-ui-workbench-INACTIVE_TAB_OUTER_KEYLINE_COLOR { color: ${border}; }
			ColorDefinition#org-eclipse-ui-workbench-INACTIVE_TAB_INNER_KEYLINE_COLOR { color: ${border}; }
			ColorDefinition#org-eclipse-ui-workbench-INACTIVE_TAB_OUTLINE_COLOR { color: ${border}; }
			ColorDefinition#org-eclipse-ui-workbench-INACTIVE_UNSELECTED_TABS_COLOR_START { color: ${chrome}; }
			ColorDefinition#org-eclipse-ui-workbench-INACTIVE_UNSELECTED_TABS_COLOR_END { color: ${chrome}; }
			ColorDefinition#org-eclipse-ui-workbench-INACTIVE_NOFOCUS_TAB_BG_START { color: ${chrome}; }
			ColorDefinition#org-eclipse-ui-workbench-INACTIVE_NOFOCUS_TAB_BG_END { color: ${chrome}; }

			/* ===== Shells, dialogs and generic containers ===== */
			Shell,
			Composite, ScrolledComposite, ExpandableComposite, Canvas, TabFolder, CLabel, Label,
			Sash, Group, RefactoringLocationControl, ChangeParametersControl, Link, FilteredTree,
			ProxyEntriesComposite, NonProxyHostsComposite, DelayedFilterCheckboxTree,
			Splitter, ScrolledPageContent, ViewForm, LaunchConfigurationFilteredTree,
			ContainerSelectionGroup, BrowseCatalogItem, EncodingSettings,
			ProgressMonitorPart, DocCommentOwnerComposite, NewServerComposite,
			NewManualServerComposite, ServerTypeComposite, FigureCanvas,
			DependenciesComposite, ListEditorComposite, WrappedPageBook,
			CompareStructureViewerSwitchingPane, CompareContentViewerSwitchingPane,
			QualifiedNameComponent, RefactoringStatusViewer,
			MessageLine, Button, SashForm, ExpandBar, PageBook, CBanner, TabItem,
			Composite > *,
			Composite > * > *,
			Group > StyledText {
			    background-color: ${background};
			    color: ${foreground};
			}

			TabFolder > *,
			CTabFolder > *,
			TabFolder > Composite > *,
			CTabFolder > Composite > *,
			TabFolder > Composite > * > * {
			    color: ${foreground};
			}

			ToolBar, CoolBar, ToolItem {
			    background-color: ${chrome};
			    color: ${foreground};
			}

			/* ===== Trim, sashes and status line ===== */
			.MTrimmedWindow, .MTrimBar, .MToolBar, .MToolControl, .MPartSashContainer,
			StatusLine, ImageBasedFrame, HeapStatus,
			#org-eclipse-ui-StatusLine, #org-eclipse-ui-StatusLine CLabel,
			#org-eclipse-ui-ProgressBar, #org-eclipse-ui-ProgressBar Canvas {
			    background-color: ${chrome};
			    color: ${foreground};
			}
			.MTrimBar#org-eclipse-ui-main-toolbar { background-color: ${chrome}; }

			/* ===== Editable controls ===== */
			Combo, CCombo, Text, Spinner, DateTime {
			    background-color: ${input};
			    color: ${foreground};
			}
			Text[style~='SWT.SEARCH'],
			Text[style~='SWT.SEARCH'] + Label {
			    background-color: ${input};
			    color: ${foreground};
			}
			Text[style~='SWT.READ_ONLY'] {
			    background-color: ${background};
			    color: ${muted};
			}
			Composite > StyledText,
			Shell [style~='SWT.DROP_DOWN'] > StyledText,
			SashForm > StyledText {
			    background-color: ${background};
			    color: ${foreground};
			}

			/* ===== Lists, trees and tables ===== */
			List, Table, Tree, RegistryFilteredTree,
			Shell Tree, Shell Table, Shell List {
			    background-color: ${background};
			    color: ${foreground};
			}
			Table, Tree {
			    swt-header-background-color: ${elevated};
			    swt-header-color: ${foreground};
			}
			TableColumn, TreeColumn {
			    background-color: ${elevated};
			    color: ${foreground};
			}

			/* ===== Progress, scales and links ===== */
			ProgressBar, ProgressIndicator {
			    background-color: ${muted};
			    color: ${foreground};
			}
			Scale, Slider {
			    background-color: ${background};
			    color: ${foreground};
			}
			Link { swt-link-foreground-color: ${link}; }
			Hyperlink, ImageHyperlink {
			    background-color: inherit;
			    color: ${link};
			}
			Twistie { color: ${foreground}; }

			/* ===== Forms toolkit (Section, Form, tabbed properties) ===== */
			Form, FormHeading {
			    background-color: ${background};
			    background: ${background};
			    color: ${foreground};
			}
			Form {
			    text-background-color: ${background};
			    tb-toggle-hover-color: ${foreground};
			    tb-toggle-color: ${foreground};
			    h-hover-full-color: ${hover};
			    h-hover-light-color: ${hover};
			    h-bottom-keyline-2-color: ${border};
			    h-bottom-keyline-1-color: ${border};
			}
			Section {
			    background-color: ${background};
			    color: ${foreground};
			    background-color-titlebar: ${elevated};
			    background-color-gradient-titlebar: ${elevated};
			    border-color-titlebar: ${border};
			    swt-titlebar-color: ${foreground};
			    tb-toggle-hover-color: ${foreground};
			    tb-toggle-color: ${foreground};
			}
			ExpandableComposite {
			    swt-titlebar-color: ${foreground};
			    tb-toggle-hover-color: ${foreground};
			    tb-toggle-color: ${foreground};
			}
			ScrolledFormText, FormText {
			    background-color: ${background};
			    color: ${foreground};
			}
			TabbedPropertyTitle > CLabel { color: ${foreground}; }
			TabbedPropertyTitle {
			    swt-backgroundGradientStart-color: ${elevated};
			    swt-backgroundGradientEnd-color: ${elevated};
			    swt-backgroundBottomKeyline1-color: ${border};
			    swt-backgroundBottomKeyline2-color: ${border};
			}
			TabbedPropertyList {
			    swt-tabNormalShadow-color: ${border};
			    swt-tabDarkShadow-color: ${border};
			    swt-tabAreaBackground-color: ${chrome};
			    swt-tabBackground-color: ${chrome};
			    color: ${foreground};
			}

			/* ===== Panes, date pickers and remaining hard-coded greys ===== */
			ViewerPane, DrillDownComposite, CompareViewerPane, CompareViewerPane > * {
			    background-color: ${background};
			    color: ${foreground};
			}
			ProgressInfoItem, ProgressInfoItem > * {
			    background-color: ${background};
			    color: ${foreground};
			}
			DatePicker, DatePicker > Text, ScheduleDatePicker, ScheduleDatePicker > Text {
			    background-color: ${input};
			    color: ${foreground};
			}
			GradientCanvas, GradientCanvas > Label {
			    background-color: ${elevated};
			    background: ${elevated};
			    color: ${foreground};
			}
			CategoryItem > GradientCanvas, CategoryItem > GradientCanvas > Label {
			    background-color: ${elevated};
			    background: ${elevated};
			    color: ${foreground};
			}
			CatalogSwitcher,
			CatalogSwitcher > ScrolledComposite > Composite > Composite,
			CategoryItem, WebSite {
			    background-color: ${background};
			    color: ${foreground};
			}
			DiscoveryItem, DiscoveryItem Label, DiscoveryItem Composite, DiscoveryItem StyledText {
			    background-color: ${elevated};
			    color: ${foreground};
			}
			DiscoveryItem Link {
			    background-color: ${elevated};
			    color: ${link};
			}
			PageSiteComposite, PageSiteComposite > CImageLabel { color: ${foreground}; }
			PageSiteComposite > PropertyTable {
			    background-color: ${input};
			    color: ${foreground};
			}
			PageSiteComposite > PropertyTable:disabled {
			    background-color: ${elevated};
			    color: ${disabled};
			}

			/* ===== Parts (views and editors) ===== */
			.MPart {
			    background-color: ${background};
			    color: ${foreground};
			}
			.MPart Composite,
			.MPart Composite > *,
			.MPart Composite > * > *,
			.MPart Label,
			.MPart CLabel,
			.MPart ScrolledForm,
			.MPart Form,
			.MPart Section,
			.MPart FormText,
			.MPart Link,
			.MPart Sash,
			.MPart Button,
			.MPart Group,
			.MPart SashForm,
			.MPart Tree,
			.MPart Table,
			.MPart List,
			.MPart Browser,
			.MPart ViewForm,
			.MPart ViewForm > CLabel,
			.MPart PageBook > Label,
			.MPart PageBook > SashForm,
			.MPart PageBook > SashForm Label,
			.MPart FilteredTree,
			.MPart RegistryFilteredTree,
			.MPart PageSiteComposite,
			.MPart DependenciesComposite,
			.MPart Text[style~='SWT.READ_ONLY'],
			.MPart FigureCanvas,
			.MPart ListEditorComposite,
			.MPart ScrolledComposite,
			.MPart ScrolledComposite ProgressInfoItem,
			.MPart Form ScrolledPageBook,
			.MPart Section > Label,
			.MPart Section Tree,
			.MPart Composite > StyledText,
			.MPart DependenciesComposite > SashForm > Section > * {
			    background-color: ${background};
			    color: ${foreground};
			}
			.MPart DatePicker,
			.MPart DatePicker > Text,
			.MPart ScheduleDatePicker,
			.MPart ScheduleDatePicker > Text,
			.MPart CCombo,
			.MPart Combo,
			.MPart Spinner,
			.MPart Text,
			.MPart SashForm > Text[style~='SWT.BORDER'] {
			    background-color: ${input};
			    color: ${foreground};
			}
			.MPart FormHeading,
			.MPart FormHeading > TitleRegion,
			.MPart FormHeading > TitleRegion > Label,
			.MPart FormHeading > TitleRegion > StyledText,
			.MPart FormHeading > CLabel {
			    background-color: ${elevated};
			    color: ${foreground};
			}
			#org-eclipse-jdt-ui-SourceView StyledText,
			#org-eclipse-wst-jsdt-ui-SourceView StyledText,
			#org-eclipse-e4-ui-compatibility-editor LayoutCanvas {
			    background-color: ${background};
			    color: ${foreground};
			}
			#org-eclipse-ui-console-ConsoleView .MPart > Composite,
			#org-eclipse-ui-console-ConsoleView .MPart StyledText,
			#org-eclipse-ui-console-ConsoleView .MPart PageBook Label {
			    background-color: ${background};
			    color: ${foreground};
			}

			/* ===== Tabs ===== */
			CTabFolder {
			    swt-unselected-hot-tab-color-background: ${hover};
			}
			CTabFolder[style~='SWT.DOWN'][style~='SWT.BOTTOM'] {
			    swt-unselected-hot-tab-color-background: ${hover};
			    swt-selected-tab-highlight: ${link};
			    swt-selected-highlight-top: false;
			}
			CTabFolder.active {
			    swt-selected-tab-highlight: ${link};
			    swt-selected-highlight-top: false;
			}
			CTabFolder Canvas,
			.MPartStack.active CTabFolder Canvas {
			    background-color: ${background};
			    color: ${foreground};
			}
			CTabFolder > Composite#ToolbarComposite { background-color: ${background}; }
			CTabFolder.MArea {
			    background-color: ${chrome};
			    swt-selected-tab-fill: ${background};
			    swt-unselected-tabs-color: ${chrome};
			    swt-outer-keyline-color: ${chrome};
			    swt-inner-keyline-color: ${chrome};
			    swt-tab-outline: ${chrome};
			}
			CTabFolder.MArea CTabItem, CTabFolder.MArea CTabItem CLabel {
			    background-color: ${chrome};
			}
			CTabItem.busy { color: ${muted}; }
			.MPartStack { swt-selected-tab-fill: ${background}; }
			.MPartStack > Composite,
			.MPartStack.active > Composite,
			.MPartStack.active.noFocus > Composite { background-color: ${background}; }
			.ModifiedDragFeedback { background-color: ${selectionBackground}; }
			""";
	// @formatter:on
}
